# Generated by Django 5.2.5 on 2025-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='qr_include_logo',
            field=models.BooleanField(default=False, help_text='Include logo in QR code'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='qr_logo_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='qr_primary_color',
            field=models.CharField(default='#000000', help_text='Primary QR color', max_length=7),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='qr_secondary_color',
            field=models.CharField(default='#FFFFFF', help_text='Secondary QR color', max_length=7),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='qr_size',
            field=models.CharField(choices=[('small', 'Small (200x200)'), ('medium', 'Medium (300x300)'), ('large', 'Large (400x400)')], default='medium', max_length=10),
        ),
    ]
