# Generated by Django 5.2.5 on 2025-10-12 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_vehicle_qr_include_logo_vehicle_qr_logo_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberMasking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_phone', models.CharField(help_text='Original phone number being masked', max_length=17)),
                ('masked_phone', models.CharField(help_text='Generated masked phone number', max_length=17)),
                ('session_id', models.UUIDField(default=uuid.uuid4, help_text='Unique session identifier', unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this masking session expires')),
                ('call_count', models.PositiveIntegerField(default=0, help_text='Number of calls made to this masked number')),
                ('last_called_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masking_sessions', to='parking.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'status'], name='parking_pho_vehicle_81094c_idx'), models.Index(fields=['masked_phone'], name='parking_pho_masked__f8d3d7_idx'), models.Index(fields=['expires_at'], name='parking_pho_expires_90d385_idx')],
            },
        ),
    ]
