# Generated by Django 5.2.5 on 2025-10-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_phonenumbermasking'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_masking_sessions',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of concurrent masking sessions allowed'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='masking_enabled',
            field=models.BooleanField(default=False, help_text="Enable number masking for this vehicle's QR code"),
        ),
    ]
