# Generated by Django 5.2.5 on 2025-12-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_subscriptionplan_max_masking_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='emergency_contact_number',
            field=models.CharField(blank=True, help_text='Emergency contact number to display in QR code', max_length=17),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='helpline_number',
            field=models.CharField(blank=True, help_text='Helpline number to display in QR code', max_length=17),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='show_emergency_contact',
            field=models.BooleanField(default=False, help_text='Show emergency contact number in QR code'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='show_helpline_number',
            field=models.BooleanField(default=False, help_text='Show helpline number in QR code'),
        ),
    ]
