# Generated by Django 5.2.5 on 2026-01-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_vehicle_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=17)),
                ('relation', models.CharField(choices=[('owner', 'Owner'), ('family', 'Family Member'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('emergency', 'Emergency Contact'), ('other', 'Other')], default='owner', help_text='Relationship to vehicle owner', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact number')),
                ('show_in_qr', models.BooleanField(default=True, help_text='Show this contact in QR code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='parking.vehicle')),
            ],
            options={
                'ordering': ['-is_primary', 'relation', 'created_at'],
                'unique_together': {('vehicle', 'phone_number')},
            },
        ),
    ]
