# Generated by Django 5.2.5 on 2026-01-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_vehiclecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecontact',
            name='relation',
            field=models.CharField(choices=[('family', 'Family Member'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('emergency', 'Emergency Contact'), ('other', 'Other')], default='family', help_text='Relationship to vehicle owner', max_length=20),
        ),
    ]
