# Generated by Django 5.2.5 on 2026-03-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_add_twilio_fields_to_masking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbermasking',
            name='masked_phone',
            field=models.CharField(help_text='Generated masked phone number or scanner number', max_length=17),
        ),
    ]
